resolver: ghc-9.2.1
extra-deps:
  - adjunctions-4.4
  - base-orphans-0.8.6
  - bifunctors-5.5.11
  - comonad-5.0.8
  - contravariant-1.5.5
  - data-default-class-0.1.2.0
  - distributive-0.6.2.1
  - dlist-1.0
  - either-5.0.1.1
  - free-5.1.7
  - groups-0.5.3
  - hashable-1.4.0.2
  - indexed-traversable-0.1.2
  - integer-logarithms-1.0.3.1
  - invariant-0.5.5
  - kan-extensions-5.2.3
  - keys-3.12.3
  - pointed-5.0.3
  - primitive-0.7.3.0
  - profunctors-5.6.2
  - random-1.2.1
  - scientific-0.3.7.0
  - selective-0.5
  - semigroupoids-5.3.7
  - semigroups-0.20
  - splitmix-0.1.0.4
  - StateVar-1.2.2
  - tagged-0.8.6.1
  - text-2.0
  - th-abstraction-0.4.3.0
  - time-compat-1.9.6.1
  - transformers-base-0.4.6
  - transformers-compat-0.7.1
  - unordered-containers-0.2.16.0
  - uuid-types-1.0.5
  - vector-0.12.3.1
  - vector-instances-3.4
  - void-0.7.3
