name: Compile, test and check the docs

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:

  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nikita-volkov/cabal-fmt.github-action@v1.0.0
      - uses: nikita-volkov/ormolu.github-action@v1.0.0
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format

  build-and-test:

    needs:
      - format

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: 8.8.4
          - ghc: latest

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.10'

      - name: Generate cabal.project.freeze
        run: cabal freeze --enable-tests --enable-benchmarks

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install deps and compile
        run: cabal build --enable-tests -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"

      - name: Test
        run: cabal test --test-show-details always

      - name: Run Haddock
        run: cabal haddock
